export const Products = [
  {
    name: 'Free shirt',
    slug: 'Free shirt',
    category: 'shirt',
    image: '/images/shirt1.jpg',
    price: 70,
    brand: 'Raymond',
    rating: 4.5,
    numReview: 10,
    countInStock: 20,
    description: 'A popular shirt',
  },
  {
    name: 'Slim shirt',
    category: 'shirt',
    slug: 'slim shirt',
    image: '/images/shirt2.jpg',
    price: 72,
    rating: 4.5,
    brand: 'Nike',
    numReview: 13,
    countInStock: 20,
    description: 'A popular shirt',
  },
  {
    name: 'smile shirt',
    category: 'shirt',
    slug: 'smile shirt',
    image: '/images/shirt3.jpg',
    price: 70,
    brand: 'Nike',
    rating: 4.6,
    numReview: 13,
    countInStock: 10,
    description: 'A popular shirt',
  },
  {
    name: 'Hot shirt',
    category: 'shirt',
    slug: 'hot shirt',
    image: '/images/shirt4.jpg',
    brand: 'Raymond',
    price: 80,
    rating: 4.0,
    numReview: 30,
    countInStock: 24,
    description: 'A popular shirt',
  },
  {
    name: 'Love shirt',
    category: 'T-shirt',
    slug: 'Love shirt',
    image: '/images/shirt5.jpg',
    price: 75,
    rating: 4.5,
    brand: 'Raymond',
    numReview: 12,
    countInStock: 24,
    description: 'A popular shirt',
  },
  {
    name: 'Pure shirt',
    category: 'T-shirt',
    slug: 'Pure shirt',
    image: '/images/shirt6.jpg',
    price: 71,
    brand: 'Nike',
    rating: 4.5,
    numReview: 19,
    countInStock: 40,
    description: 'A popular shirt',
  },
  {
    name: 'Glorias shirt',
    category: 'T-shirt',
    slug: 'Glorias shirt',
    image: '/images/shirt7.jpg',
    price: 60,
    rating: 4.5,
    brand: 'Raymond',
    numReview: 10,
    countInStock: 20,
    description: 'A popular shirt',
  },
  {
    name: 'Classic T-shirt',
    category: 'T-shirt',
    slug: 'classicT-shirt',
    image: '/images/shirt8.jpg',
    price: 68,
    brand: 'Nike',
    rating: 4.5,
    numReview: 19,
    countInStock: 30,
    description: 'A popular shirt',
  },
];
